[package]
name = "cytosol-hir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cytosol-syntax = { path = "../cytosol-syntax" }
id-arena = "2"
thiserror = "1"
petgraph = "0.5"
ahash = "0.7"