[package]
name = "cytosol-runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cytosol-hir = { path = "../cytosol-hir" }
fn_ops = "0.1.0"
rand = "0.8"
ahash = "0.7"